// Complete English facet registry: latest q=* export first, then exact prior values.
// Arabic facets/values and duplicate/internal search facets are intentionally excluded.
// Keep Price dynamic; never replace it with fixed priceBucket values.
'use strict';

module.exports = Object.freeze({
    "audience_uFilter": {
        "filter_name": "Gender",
        "facet_name": "audience_uFilter",
        "values": [
            "Women",
            "Men",
            "Girls",
            "Boys"
        ],
        "dynamic_numeric_range": false
    },
    "level2CategoryName_uFilter": {
        "filter_name": "Category",
        "facet_name": "level2CategoryName_uFilter",
        "values": [
            "Kurta Sets",
            "Lehengas",
            "Dresses",
            "Sarees",
            "Topwear",
            "Pant Sets",
            "Earrings",
            "Footwear",
            "Bags",
            "Kurtas",
            "Bottomwear",
            "Necklaces",
            "Jewellery Sets",
            "Sherwanis",
            "Gowns",
            "Co-ord Sets",
            "Jackets And Sets",
            "Jumpsuits",
            "Ethnic Jackets",
            "Ethnic Dresses",
            "Bandhgalas",
            "Ethnic Co-ord Sets",
            "Rings",
            "Suits And Tuxedos",
            "Bracelets",
            "Scarves & Stoles",
            "Blazers & Sets",
            "Bangles",
            "Hair Accessories",
            "Dupattas",
            "Maang Tikkas",
            "Brooches And Pins",
            "Coats And Waistcoats",
            "Belts",
            "Matha Pattis",
            "Shawls",
            "Hathphools",
            "Button Sets",
            "Swimwear",
            "Co-Ord Sets",
            "Nose Rings",
            "Malas",
            "Bow Ties And Pocket Square Sets",
            "Anklets",
            "Kalangis",
            "Vests",
            "Passas",
            "Ethnic Co-Ord Sets",
            "Kaleeras",
            "Rakhis"
        ],
        "dynamic_numeric_range": false
    },
    "level3CategoryNames_uFilter": {
        "filter_name": "Sub Category",
        "facet_name": "level3CategoryNames_uFilter",
        "values": [
            "Straight Kurta Sets",
            "Lehenga Cholis",
            "Sharara Sets",
            "Anarkali Sets",
            "Casual Shirts",
            "Pre-Draped Sarees",
            "Palazzo Sets",
            "Midi Dresses",
            "Classic Kurta Sets",
            "Nehru Jacket Sets",
            "Dangler Earrings",
            "Maxi Dresses",
            "Classic Sarees",
            "Kaftan Sets",
            "Handloom Sarees",
            "Kurtas",
            "Mini Dresses",
            "Flats",
            "Clutches",
            "Jacket & Cape Lehengas",
            "Kaftan Dresses",
            "Dhoti Sets",
            "Salwar Sets",
            "Tunics & Kurtis",
            "Blouses",
            "Trousers",
            "Jackets",
            "Churidar Sets",
            "Potlis/Batwas",
            "Heels",
            "Gowns",
            "Chokers",
            "Handbags",
            "Pendant Necklaces",
            "Tops & Tunics",
            "Stud Earrings",
            "Gharara Sets",
            "Statement Rings",
            "Jacket & Angarkha Kurta Sets",
            "Stoles",
            "Mules",
            "Shirt Dresses",
            "Skirts",
            "Chandbali Earrings",
            "Party Gowns",
            "Juttis",
            "Tiered Dresses",
            "Jhumka Earrings",
            "Fit & Flare Dresses",
            "Asymmetrical Dresses",
            "Midi Dress",
            "Maxi Dress",
            "Mini Dress",
            "Jacket Sets",
            "Formal Shirts",
            "Blazers",
            "Palazzos",
            "Half & Half Sarees",
            "Bangle Sets",
            "Chandelier Earrings",
            "Blazer Sets",
            "Layered Necklaces"
        ],
        "dynamic_numeric_range": false
    },
    "designerName_uFilter": {
        "filter_name": "Designers",
        "facet_name": "designerName_uFilter",
        "values": [
            "Arihant Rai Sinha",
            "Sangeeta Boochra",
            "Petite Pomme",
            "Soup By Sougat Paul",
            "Samyukta Singhania",
            "Three",
            "Kasbah",
            "Riana Jewellery",
            "FAYON KIDS",
            "Do Taara",
            "Dash And Dot",
            "Nazaakat By Samara Singh",
            "Swabhimann",
            "Raghavendra Rathore Jodhpur",
            "Twenty Nine",
            "Foot Fuel",
            "Khwaab By Sanjana Lakhani",
            "Kalista",
            "Paisley Pop",
            "Nitika Gujral",
            "Label Niti Bothra",
            "Tarun Tahiliani",
            "Cosa Nostraa",
            "Ridhi Mehra",
            "Pankaj & Nidhi",
            "Koai",
            "Rajdeep Ranawat",
            "Rohit Bal",
            "Payal Singhal",
            "Chandrima",
            "Smriti By Anju Agarwal",
            "Asuka",
            "Punit Balana",
            "5elements",
            "Joules by Radhika",
            "Payal Pratap",
            "Zevar By Geeta",
            "Shyam Narayan Prasad",
            "Siddartha Tytler",
            "Masaba",
            "Sheetal Batra",
            "Dugran By Dugristyle",
            "Anamika Khanna",
            "Kharakapas",
            "Rabani & Rakha",
            "Kora",
            "Nikita Mhaisalkar",
            "Gargee Designers",
            "Paulmi And Harsh",
            "Samant Chauhan",
            "Aham-Vayam",
            "Mayank Modi - Men",
            "Mahima Mahajan",
            "Kirti Agarwal - Pret N Couture",
            "Vivinia By Vidhi Mehra",
            "Shahin Mannan",
            "Seema Thukral",
            "Pants And Pajamas",
            "Sica Jewellery",
            "Nautanky",
            "Arvino",
            "Itrh",
            "Seema Gujral",
            "Sue Mue",
            "Prisho",
            "Deepika Arora",
            "Pomcha Jaipur",
            "Mandira Wirk",
            "Oroh",
            "Rishi and Vibhuti",
            "Jhambthreads",
            "Devnaagri",
            "Amit Arora",
            "Aseem Kapoor",
            "Kaveri",
            "Shivani Bhargava",
            "Saaksha & Kinni",
            "Shradha Hedau Footwear Couture",
            "Neha Khullar",
            "Soniya G",
            "Ampm",
            "Esha L Amin",
            "Hirika & Dhruti",
            "Linen Bloom",
            "Rng Safawala",
            "SPRING BREAK",
            "Gopi Vaid",
            "Limerick By Abirr N' Nanki",
            "Mishru",
            "PAARSH",
            "Aakaar",
            "Archana Kochhar",
            "Gulabo By Abu Sandeep",
            "Vvani by vani vats",
            "Ajiesh Oberoi",
            "Urvashi Kaur",
            "Gauri & Nainika",
            "Siddhartha Bansal",
            "Raabta By Rahul",
            "Queens Jewels",
            "ANGAD SINGH",
            "Jatin Malik",
            "Clos",
            "Charkhee",
            "Dolly J",
            "Anantaa By Roohi",
            "Aariyana Couture",
            "KRISHNA MEHTA",
            "Runit Gupta",
            "YOSEBA",
            "Chrkha",
            "MATI",
            "The Alter",
            "Shorshe Clothing",
            "Kanyaadhan By Dhirajaayushi",
            "Moh-Maya By Disha Khatri",
            "Rage Attire-Sweta Saria",
            "Pooja Rajgarhia Gupta",
            "SHUTIQ",
            "B'Infinite",
            "Artimen",
            "Varun Bahl",
            "Two Sisters By Gyans",
            "Swatti Kapoor",
            "The Purple Sack",
            "JAYATI GOENKA",
            "Surabhi Arya",
            "Suruchi Parakh",
            "Weaver Story",
            "Arcvsh By Pallavi Singh",
            "Abraham And Thakore",
            "Ekaya Banaras",
            "Miss Jo",
            "Mac Duggal",
            "Aneesh Agarwaal",
            "Salil Bhatia",
            "Shruti S",
            "The Dramebaaz CO",
            "BABITA M",
            "Monk & Mei By Sonia Anand",
            "SHASHA GABA",
            "Therealb",
            "Bijoux By Priya Chandna",
            "Son Of A Noble Snob",
            "Cord",
            "Amrit Dawani",
            "Khat",
            "Outhouse",
            "RAAS LIFE",
            "MADDER MUCH",
            "Bubber Couture",
            "Mimamsaa",
            "Kalpana Naik",
            "Naaritva Banaras",
            "Perona",
            "Siddhant Agrawal",
            "Ritika Mirchandani",
            "One Not Two",
            "The Tan Clan",
            "OurDve",
            "Shlok Jewels",
            "Karisa Designs",
            "Ahi Clothing",
            "Studio Bagechaa",
            "Dhruv Vaish",
            "Philocaly",
            "House of Vian",
            "Kritika Dawar",
            "Preevin",
            "RI.Ritu Kumar",
            "Kalighata",
            "Torani",
            "Charu Makkar",
            "Varun Chakkilam",
            "Asaga",
            "Balance by Rohit Bal",
            "Amit Aggarwal",
            "Masumi Mewawalla",
            "Farha Syed",
            "Vinusto",
            "Shwetanga",
            "ESME",
            "Ilk",
            "Sahil Kochhar",
            "Meenagurnam",
            "Namrata Joshipura",
            "Nayaab By Sonia",
            "Partykles",
            "Just Shradhas",
            "Shruti Sancheti",
            "Manish Nagdeo",
            "Terra Luna",
            "Lil Angels",
            "Nupur Kanoi",
            "Tiesta",
            "Hilo Design",
            "Ritu Kumar",
            "Tiber Taber",
            "Kokommo",
            "Oja",
            "Neha Gursahani",
            "Surmaye",
            "Tad Accessories",
            "Neora By Nehal Chopra",
            "Chhaya Mehrotra",
            "MR. Ajay Kumar",
            "BANANA labs",
            "Jubinav Chadha",
            "Anushree Reddy",
            "Kaka Calcutta",
            "PRERTO",
            "Aditi Gupta",
            "Charu And Vasundhara",
            "Style Junkiie",
            "K-Anshika",
            "Label Neeti",
            "Roqa",
            "Dohr India",
            "Nadima Saqib",
            "Safaa",
            "Yuvraani Jaipur",
            "Sarab Khanijou",
            "Bannhi By Priyanka Rathore",
            "Zoon",
            "Basanti Kapde aur Koffee",
            "Payal & Zinal",
            "Jajaabor",
            "Vedika M",
            "Bauble Bazaar",
            "Kommal Sood",
            "NACHIKETBARVE",
            "Karaj Jaipur",
            "ROHIT DOSHI",
            "Zaza By Somya",
            "Sanjana Reddy Designs",
            "Dusala",
            "Priyanka Raajiv",
            "Dang Shoes",
            "Mero Jewellery",
            "Suhani Pittie",
            "The Iaso",
            "Bhanuni By Jyoti",
            "Lashkaraa",
            "Stoique",
            "Chambray & Co.",
            "Komal Shah",
            "LEH STUDIOS",
            "Shreyansh Designs",
            "ISHA GUPTA TAYAL",
            "Wednesday Lifestyle",
            "Shriya Som",
            "Betrue",
            "Cedar & Pine",
            "Little Brats",
            "Ayaka",
            "Label Moni K",
            "Littleens",
            "Ewoke",
            "Roohbyridhimaa",
            "Toplove",
            "Begum",
            "Shikhar Sharma",
            "Echke",
            "Wabi Sabi By Anshum-Ritesh",
            "Issa Studio By Chetana & Swathi",
            "Moh India",
            "Kavya Singh Kundu",
            "Ruby Raang",
            "Neetiandmudita",
            "Around Always",
            "Chhavvi Aggarwal",
            "Opalina Soulful Jewellery",
            "Raw & Rustic By Niti Bothra",
            "Sana K luxurious Footwear",
            "The Garnish Company",
            "Kay Kay",
            "Minaki",
            "Shingora",
            "Amrood",
            "Mehak Murpana",
            "Vaani Beswal",
            "Yajy By Aditya Jain",
            "Awigna",
            "Contrast By Parth",
            "Surbhi Gupta",
            "Thee Modern Roots",
            "Varnika Arora",
            "Janki India",
            "Ankur J",
            "Ridhima Bhasin",
            "Kalakaari By Sagarika",
            "House Of Three",
            "NIDHIKA SHEKHAR",
            "1999ad By Amita & Deepak",
            "Swati Vijaivargie",
            "Aroop Shop India",
            "Ahmev",
            "LATHA PUTTANNA",
            "Pinkcow designs pvt ltd",
            "Vandana Sethi",
            "ZiP by Payal & Zinal",
            "Ituvana",
            "Advait",
            "Kritika Murarka",
            "Priya Chaudhary",
            "Taika By Poonam Bhagat",
            "Amaare",
            "Line Out Line",
            "Chamee & Palak",
            "Saga Jewels",
            "BAIDEHI",
            "Prata",
            "Amrta By Guneet Kondal",
            "Chatenya Mittal",
            "SHAZA",
            "CAPISVIRLEO",
            "DIOSA PARIS JEWELLERY",
            "Geroo Jaipur",
            "I Am Design",
            "Lovetobag",
            "Modarta",
            "NOIB",
            "Anu Pellakuru",
            "Bohame",
            "Esha Koul",
            "Miku Kumar",
            "Rirasa",
            "Omana By Ranjana Bothra",
            "Swatee Singh",
            "AMYRA",
            "Maisolos",
            "Sheeshakari",
            "Thetaa",
            "Redpine Designs",
            "House Of Tuhina",
            "ISADAA BY ROTNA DUTT",
            "Pasha India",
            "KEITH GOMES",
            "Vana Ethnics",
            "Tamanna Punjabi Kapoor",
            "House Of Supriya",
            "Littlecheer",
            "The Home Affair",
            "Nazar By Indu",
            "Taisha",
            "Vivek Karunakaran",
            "Mirroir",
            "Pallavi Jaipur",
            "Archana Shah",
            "Priyanka Jain",
            "Cute Couture",
            "HRISHA",
            "OMI",
            "Sakshi Khetterpal",
            "Taro",
            "Anaar",
            "Cupid Cotton",
            "Lil Drama",
            "Naina Jain",
            "Pashma",
            "Rhua",
            "Arpita Mehta",
            "Studio22 By Pulkita Arora Bajaj",
            "Zevar King",
            "Anaash",
            "Geisha Designs",
            "Maison Shefali",
            "Doux Amour",
            "Jigar Mali",
            "Prestones",
            "Krisha Sunny Ramani",
            "Lajjoo C",
            "Vinita Bhansali",
            "Whimsical By Shica",
            "Millionaire",
            "Studio Surbhi",
            "BAISE GABA",
            "Febo6",
            "Divya Aggarwal",
            "Blue Lotus Design",
            "Vanshika Agarwal Label",
            "Meher By Islie",
            "Pooja Peshoria",
            "Vaayu",
            "Bhumika Sharma",
            "Dilnaz",
            "17:17 By Simmi Saboo",
            "House Of Varada",
            "Sameer Madan",
            "Bblingg",
            "Debyani + CO",
            "Leela By A",
            "Arpita Sulakshana",
            "Byb Premium",
            "Eeda",
            "OTT",
            "Pallavi Poddar",
            "Studio Rigu",
            "KA-Sha",
            "Kahani Lush",
            "APT FOREVER",
            "P & S CO",
            "Trov",
            "Ikshita Choudhary",
            "The Little Celebs",
            "Vesture",
            "Zariaah",
            "Mani Bhatia",
            "Ohaila Khan",
            "Papa Dont Preach",
            "Label Priyanka Kar",
            "MUKTI AND KAVITH CASA",
            "MATSYA",
            "Merakus",
            "Naaz By Noor",
            "Supria Munjal",
            "Mrunalini Rao",
            "Ruchika Lath Label",
            "MI Dulce AN'YA",
            "Palak & Mehak",
            "SOBARIKO",
            "Zal From Benaras",
            "Deep Thee",
            "Ozeqo",
            "Tribe Amrapali",
            "Adora By Ankita",
            "Chaashni By Maansi And Ketan",
            "House of Webhin",
            "Meesa",
            "Parul Gandhi",
            "Pink City by Sarika",
            "Devina Juneja",
            "NUHH",
            "ASRUMO",
            "Dhwani Bansal Jewellery",
            "Jade By Ashima",
            "Punit Arora",
            "Rocky Star",
            "Akhl",
            "Arjan Dugal",
            "Gaurav katta",
            "Kalp",
            "Anana",
            "Etasha By Asha Jain",
            "The Aarya",
            "Countrymade",
            "Ellemora Fashions",
            "Istya",
            "Mustard Moon By Neyha And Vrinda",
            "OFRIDA",
            "Studio 113",
            "ZARIIN",
            "Aditi Somani",
            "Azeera",
            "Nitisha Kashyap",
            "Priyal Prakash",
            "SUHINO",
            "House Of Kosha",
            "Kicky & Perky",
            "Menero",
            "Niloufer By Aasif Ally",
            "Raasa",
            "Raghavendra Rathore Blue",
            "Fellmonger",
            "Kiran Uttam Ghosh",
            "Mithi Supari",
            "Preeti Mehta",
            "Surbhi Shah",
            "Vivek Patel",
            "Aamra By Lavanya",
            "Nidhi Bhandari",
            "Rajiramniq",
            "Enamour By Radha",
            "Namasya",
            "Noonoo",
            "Ruchi Marodia",
            "SHILPI GUPTA",
            "Shimona",
            "Studio6 Jewels",
            "MAALICIOUS JEWELRY",
            "Ruhr India",
            "Surkh Syahi",
            "Gulabo Jaipur",
            "Reeti Arneja",
            "Rhe-Ana",
            "One Knot One By Ashna",
            "Orthodox",
            "Parshya",
            "Priyanka Haralalka",
            "Rainas",
            "Shop Nirvanaa",
            "Yavi",
            "dmodot",
            "Deme By Gabriella",
            "Kyra By Bhavna",
            "RANNA GILL",
            "Vara By Vibha N Priti",
            "saina kapoor",
            "Eli Bitton",
            "Kameez",
            "Libas Cafe by Nidhi & Ashish",
            "MINIME ORGANICS",
            "Origani",
            "Preeti S Kapoor",
            "LA Dee DA",
            "MAISARA JEWELRY",
            "Richa Khemka",
            "Rimi Nayak",
            "THE COTTON STAPLE",
            "Til",
            "Ananya Agrawal Label",
            "House Of Koa",
            "July Issue",
            "Sven Suits",
            "Isharya",
            "Onaya",
            "Prahnaaya",
            "Affroz",
            "Jyoti Sachdev Iyer",
            "Wazir C",
            "Essay By Sumedha Agrawal",
            "Pankhuri By Priyanka",
            "Pouli Pret",
            "Shetab Kazmi",
            "Swish By Dolcy And Simran",
            "Tiny Colour",
            "Design O Stitch",
            "Lacquer Embassy",
            "RINESSA",
            "Reena Sharma",
            "Abhinav Mishra",
            "COUTURE BY NIHARIKA",
            "Preeti Mohan",
            "JILMIL DREAMWEAR",
            "Midushi Bajoria",
            "Saisha",
            "Shikha Mehta",
            "Tussah By Siddhi Shah",
            "Upavita",
            "Vanshik",
            "Saaj By Ankita",
            "Sejal Kamdar",
            "Aum By Asit And Ashima",
            "ChhavI'S Jewels",
            "Chokhi Chorri",
            "EASE",
            "Neeta Bhargava",
            "Sandalwali",
            "Satya Paul",
            "Shreeka",
            "Sunandini",
            "Sunita Bhandari",
            "A Little Fable",
            "Adwita Bags & Jewels",
            "Anuka Jewels",
            "Courtyard By Abhi",
            "Drishti & Zahabia",
            "Mushio",
            "Nikita Vishakha",
            "Rejuvenate Jewels",
            "Seams Pret And Couture",
            "Shashank Arya",
            "The Pony & Peony Co.",
            "Veera Wear",
            "AM by Anita Mittal",
            "Dressfolk",
            "HOUSE OF TA-YA",
            "Miraki",
            "Mnsh",
            "Tara And I",
            "Tashee",
            "Dyelogue",
            "Rahul Singh",
            "Voyce Jewellery",
            "Dhaari",
            "FOREVER NOOR",
            "Linetribe",
            "Nirjara",
            "POZRUH",
            "Bling Empire",
            "Jodi",
            "PIRI INDIA",
            "Rishi And Soujit",
            "Sole House",
            "Verano By Tanya",
            "Amaara Jewels",
            "Bhawna Sethi",
            "DE'Anma",
            "House Of Eda",
            "Sheela Suthar",
            "Silai Studio",
            "Label Deepshika Agarwal",
            "MRJEWELS",
            "Meadow",
            "Tatwa",
            "Aryavir Malhotra",
            "Bandhani",
            "Echostudio",
            "Krishna Padia",
            "Totapari",
            "Vasstram",
            "Zazu",
            "Kunwarani Ritu",
            "Peenacolada",
            "The Madras Trunk",
            "Born Flash",
            "Jigar & Nikita",
            "Label Astha Chhabra",
            "Priti Sahni",
            "Sonal Pasrija",
            "Bohobi",
            "Darshika Menswear",
            "Label Sanya Gulati",
            "Madzin",
            "Divya Kanakia",
            "Eleven Brothers",
            "Emblaze",
            "Parul And Preyanka",
            "So Us By Sougatpaul",
            "Kaaj Button X AZA",
            "Midori By Sgv",
            "Prevasu",
            "Radhika Agrawal Jewels",
            "Saim",
            "Show Shaa",
            "Studio Moda India",
            "Medha",
            "Notsosure",
            "PREET KAUR",
            "Rimple Agrawal",
            "Roze",
            "Savaaya",
            "Tanu Malhotra",
            "Dev And Viv",
            "Silky Bindra",
            "Tamaraa By Tahani",
            "Casa Ninos",
            "Eeksha",
            "Kapda Dori",
            "Muvazo",
            "Pinup By Astha",
            "House Of Fett",
            "MR Brat",
            "Nirraamyaa",
            "The Loom Art",
            "Unallume By Nisha",
            "AK-OK",
            "Daljit Sudan",
            "Inej",
            "Label Mansi Nagdev",
            "Manner",
            "Moledro",
            "Basil Leaf",
            "Cilvr",
            "Kai Resortwear",
            "Shruti Jalan",
            "That Thing You Love",
            "The Whole Nine Yards",
            "Akashi Clothing",
            "Indigo Dreams",
            "Missprint",
            "Puneet Gupta",
            "Alpona Designs By Soham Acharya",
            "Domani",
            "Pocketful Of Cherrie",
            "Poppi",
            "Ranian",
            "The Plum Bum",
            "AMRIN KHAN",
            "Boxwish By Bhumika",
            "Ishhaara",
            "Krutiarts",
            "Label Muslin",
            "Studio Radical",
            "Trupti Mohta",
            "Vidhi Wadhwani",
            "House Of Akshata",
            "Myaara",
            "Osaa By Adarsh",
            "Swati Wadhwani Couture",
            "Aeshaane",
            "Karishma Khanduja Bareilly",
            "Tarini Vij",
            "Amisha Kothari",
            "Five Point Five",
            "Fuchsia by aashaka mehta",
            "Kkarma Accessories",
            "Nakul Sen",
            "Siyona By Ankurita",
            "The Right Cut",
            "Preeti Jhawar",
            "Saksham & Neharicka",
            "Shloka Khialani",
            "Vantier",
            "Zwaan",
            "Abkasa",
            "Amaltas Couture",
            "Escape By Aishwarya",
            "Kangana Trehan",
            "Label Flamingo By Vrinda",
            "Amoree by Shikha Chaudhry",
            "Kavith",
            "Naintara Bajaj",
            "Premya By Manishii",
            "Sajeda A Lehry",
            "Hetal Shah",
            "SG Collection By Sonia Gulrajani",
            "Shachi Sood",
            "Aamli",
            "Darleen Kids Couture",
            "Loka By Veerali Raveshia",
            "Summer By Priyanka Gupta",
            "Tasuvure Indes",
            "VIVEDKIDS",
            "Sephyr",
            "Surily G",
            "Anshu Wadhwa",
            "Dania Siddiqui",
            "Irrau By Samir Mantri",
            "Label Earthen",
            "Damoiselle",
            "Kaaj Button",
            "Oshi By Shikha",
            "Sonia Khatri",
            "Chotibuti",
            "HOUSE OF ARMUSE",
            "Richa Jaisinghani Label",
            "Tizora",
            "Breathe By Aakanksha Singh",
            "Imlee Jaipur",
            "Lasha",
            "Pocket Stories",
            "Studio Error",
            "All Boy Couture",
            "Char Chaand",
            "Label Shristi Chetani",
            "NA-KA",
            "Prateek Munjal",
            "Rajat K Tangri",
            "Richaa Goenka",
            "The Summer House",
            "ASTHA NARANG",
            "Aakansha Gupta",
            "Myoho",
            "Prama By Pratima Pandey",
            "SAANJH BY LEA",
            "The Royaleum",
            "Vaaya",
            "ZOOP MEN",
            "Modanta Footwear",
            "Vasundhara",
            "Vishwa By Pinki Sinha",
            "Almaari By Pooja Patel",
            "Eena",
            "Koswi",
            "Neha Mehra",
            "Pooja-Keyur",
            "Renee label",
            "Torque By Merge",
            "Trendy Tokari",
            "Verb By Pallavi Singhee",
            "A Humming Way",
            "Aisha Rao",
            "Jiya by Veer Design Studio",
            "Juanita By Shubhda",
            "Kashmiraa",
            "Label Ivish",
            "Mehak Sharma",
            "CHOOSE KIND",
            "Esha Arora",
            "Gazab by Miku Kumar",
            "Kaari",
            "Sabe",
            "Vikram Phadnis",
            "Xago",
            "Ekavira",
            "Gaurish Bespoke Jewellery",
            "Neitri",
            "Sinjhar",
            "Tisharth by Shivani",
            "Apeksha Jain Label",
            "Huemn",
            "Pooja Wang",
            "Prihan Luxury Jewelry",
            "Raj Arora",
            "The Episode",
            "Ankita Shahabadi",
            "Aurouss",
            "BO Tree",
            "MINI SONDHI",
            "Nemaani",
            "Nidhi Kejriwal",
            "The Leather Garden",
            "Manika Nanda",
            "Negra Elegante",
            "Nitara Dhanraj Label",
            "OHH CROW",
            "Palak Khandelwal",
            "Ronak And Shruti",
            "Salt And Spring",
            "Heel Your Sole",
            "Little Bansi",
            "Nauvab",
            "SHIAN",
            "Shikha Malik",
            "Sunita Nagi",
            "The White Tree Studio",
            "ASHNA VASWANI",
            "Cin Cin",
            "Rashika Sharma",
            "Shivani Awasty",
            "9899",
            "Aaroh By Dolly",
            "Dark Hour",
            "Grass & Sunshine",
            "Harshita Singhvi",
            "Ozel",
            "Pleats By Aruni",
            "Priti Prashant",
            "The little tales",
            "Vedangi Agarwal",
            "Indian Summer Story",
            "Little Boys Closet",
            "Mozaati",
            "Muskann Kapadiaa",
            "NOTEBOOK",
            "Nafs",
            "Nandita Thirani",
            "AMIT BEHKI",
            "Akara",
            "Cham Cham",
            "Dhi",
            "House Of D\"Oro",
            "Maayera Jaipur",
            "Meghstudio",
            "Baaro Masi",
            "Presto Couture",
            "Cilwana Studio",
            "Disha Muchhala",
            "Mamma Plz",
            "Mukta Sabharwal",
            "PS Men By Payal Singhal",
            "Reistor",
            "Sonali Gupta",
            "Anshika Tak Label",
            "Heartistry by Anky",
            "Kisakshi Jaipur",
            "Kyra By Nina + Deepika",
            "Opus Atelier",
            "Qala Clothing",
            "Quench A Thirst",
            "Ranbir Mukherjee Calcutta",
            "Studio A",
            "Angad Creations",
            "Lavina Sippy",
            "Maison Aguise",
            "Mayyur Girotra Couture",
            "Koashee By Shubitaa",
            "Nine By Janine",
            "Pop Sugar",
            "Priyanka Singh",
            "Aroka",
            "Cherie D",
            "Kavita Bhartia",
            "Label Nimbus",
            "Shalkii",
            "Tussya",
            "Arun verma",
            "Atelier Shikaarbagh",
            "Label Kiaa",
            "Nimbu Mirchi",
            "SCHON ZAPATO",
            "Tan & Loom",
            "Turqidz By Shweta Aggarwal",
            "World of Sugandh",
            "Amreli Jaipur",
            "BAANI KHURANA",
            "ClutcH'D",
            "Priyaa",
            "Ria Shah Label",
            "She'll",
            "Amit GT",
            "Dajwaree",
            "Moontara",
            "Papa Don't Preach Accessories",
            "Rachit Khanna",
            "singhanias",
            "Day And Mood",
            "Joy Mitra",
            "LAHARIO",
            "Label Ankush Jain",
            "Niamh By Kriti",
            "Payal Jain",
            "Shweta Aggarwal",
            "Tuli",
            "Vedika Soni",
            "Whitemuds",
            "Yoshita Couture",
            "Aangan By Parul",
            "Adi By Aditya Khandelwl",
            "Alam By Tulsi Patel",
            "Dheeru Taneja",
            "Essemm",
            "Heena Mittal",
            "House Of Kotwara",
            "Mauli Cashmere",
            "Nadine Dhody",
            "Rias Jaipur",
            "Rina Dhaka",
            "Shikha And Srishti Design",
            "Antar Agni",
            "Econock Studio",
            "House Of Vitti India",
            "Kavitha Gutta",
            "Megha Garg",
            "Mehar",
            "Moirra",
            "Saahiil Kapoor",
            "Sana Barreja",
            "Sandhya Shah",
            "Shagun Nagi The Label",
            "Sitaraa",
            "Beau Monde",
            "Divi By Sonal Khandelwal",
            "House of Exotique",
            "Sachkiran Bimbra",
            "Samatvam By Anjali Bhaskar",
            "Sole Mates by Palak",
            "Zilaire",
            "Zosia",
            "Akanksha Mago",
            "Aman Takyar",
            "JAYANTI REDDY",
            "Khamaj India",
            "Ornamaas",
            "AFRIYA",
            "Islie By Priya Jain",
            "Khajoor Studio",
            "Kozasko",
            "Miri",
            "Mityan",
            "PRAVALIKA KOLA",
            "Parneet Gujral",
            "Rasasvada",
            "Reeti Arneja - Theklub",
            "Seema Nanda",
            "Sonali Methi",
            "Swati Golyan",
            "APRICOTKIDS",
            "Bhavna Kumar",
            "Cinderella By Heena Yusuf",
            "Free Sparrow",
            "Kaynaat By Aanchal Sawhney",
            "Megha Bansal",
            "Neelu And Manvi",
            "Project Bandi",
            "Tajiri",
            "Veruschka By Payal Kothari",
            "Chisel By Meghna Ramrakhiya",
            "Karishma Kajaria",
            "Kasturi Kundal",
            "Kiyohra",
            "NÉVOH",
            "Peeli Dori",
            "Vedant G",
            "Ashutosh Joshi",
            "Bag Head",
            "Beige",
            "Brahmand By Vertika Kalra",
            "GUL BY AISHWARYA",
            "ITRANA",
            "Lavanya Ahuja",
            "Maison Blu",
            "PS Pret By Payal Singhal",
            "Astha Batra",
            "Brinda Sneha",
            "Decemberbyvivek",
            "House of Zyrra by Laxmishriali",
            "Petticoat Lane By Divya",
            "Pnk Isha Arora (Pink)",
            "Senren By Eshana Raut",
            "Yassio",
            "Isa By Dolly Wahal",
            "Kalighata Pret",
            "Kiran Kalsi",
            "Label Lila",
            "Meghna Panchmatia",
            "Nayantaara",
            "Tuhina Srivastava",
            "Atbw",
            "BAHAARA BY DIVYA NARULA",
            "DAREISS",
            "Eclat By Prerika Jalan",
            "House Of Karmah",
            "K&A By Karishma and Ashita",
            "Label Nitika",
            "Ode Jewels",
            "Omal Sindwani",
            "SMARS JEWELRY",
            "Saniya Sharma",
            "Bunka",
            "Leh Studios",
            "Baise Gaba",
            "SALIL BHATIA",
            "ABRAHAM AND THAKORE",
            "Rohit Doshi",
            "love",
            "Kiki",
            "KIHOY",
            "Madhav Agasti",
            "Rajesh Pratap Singh",
            "Nikasha",
            "Evra By Nikita",
            "Himani Punatar",
            "Payal and Rishab",
            "Roza",
            "Triune",
            "Qbik",
            "Mukti And Kavith Casa",
            "Madder Much",
            "Monika Mathuria Datta",
            "Anmol Kakad",
            "Honey&Me",
            "Poochkie",
            "Little Loom",
            "Nero India",
            "Agraj Jain",
            "Banana Labs",
            "Dot",
            "Soleart",
            "Kanj By Priyanka A Sakhuja",
            "Sarang Kaur",
            "Chal Jooti",
            "arani label",
            "Shahmeen Husain",
            "Spring Break",
            "Mint N Oranges",
            "Fairies Forever",
            "Anita Dongre",
            "Krishna Mehta",
            "Nikunj By NIIDHI BAJAJ"
        ],
        "dynamic_numeric_range": false
    },
    "attrPattern_uFilter": {
        "filter_name": "Pattern",
        "facet_name": "attrPattern_uFilter",
        "values": [
            "Floral",
            "Solid",
            "Ornamental",
            "Symmetrical",
            "Embroidered",
            "Geometric",
            "Printed",
            "Striped",
            "Buti",
            "Textured",
            "Self Design",
            "Abstract",
            "Colorblocked",
            "Paisley",
            "Checkered",
            "Cascading",
            "Dyed",
            "Clustered",
            "Graphic",
            "Patchwork",
            "Animal Print",
            "Faded",
            "Camouflage",
            "Brocade",
            "Multicolor",
            "ornamental",
            "symmetrical"
        ],
        "dynamic_numeric_range": false
    },
    "attrTypeOfWork_uFilter": {
        "filter_name": "Type of Work",
        "facet_name": "attrTypeOfWork_uFilter",
        "values": [
            "Embroidery",
            "Sequins",
            "Beads",
            "Pearls",
            "Zari",
            "Stones",
            "Crystals",
            "Cut work",
            "Mirrors",
            "Tassels",
            "Gota Patti",
            "Lace",
            "Applique",
            "Diamonds",
            "Metallic Thread",
            "Floral",
            "Fringe",
            "Fabric Flowers",
            "Rhinestones",
            "Patchwork",
            "Ruffles",
            "Foil Printing",
            "Sequin",
            "Studs",
            "Bows",
            "Piping",
            "Gemstones",
            "Chains",
            "Feathers",
            "Floral Motifs",
            "Geometric",
            "Smocking",
            "Buckles",
            "Thread",
            "Mirror",
            "Cutdana",
            "Zardozi",
            "Brooches",
            "Pom-poms",
            "Floral Print",
            "Glitter",
            "Thread Work",
            "Plain",
            "Resham",
            "Pearl",
            "Bead",
            "Mirror Work",
            "aari",
            "Gota",
            "Faux Diamonds",
            "Thread Embroidery",
            "Printed",
            "Machine Embroidery",
            "Resham Embroidery",
            "Digital Print",
            "Enamel",
            "Chikankari",
            "Dabka Work",
            "Embroidered",
            "Pitta Work",
            "Aari Taari",
            "Block Print",
            "Cross Stitch",
            "Dabka",
            "Hand Painted"
        ],
        "dynamic_numeric_range": false
    },
    "size_uFilter": {
        "filter_name": "Size",
        "facet_name": "size_uFilter",
        "values": [
            "M",
            "L",
            "S",
            "XL",
            "XS",
            "XXL",
            "3XL",
            "4XL",
            "5XL",
            "6XL",
            "FREE SIZE",
            "7-8 Y",
            "6-7 Y",
            "5-6 Y",
            "4-5 Y",
            "8-9 Y",
            "3-4 Y",
            "9-10 Y",
            "2-3 Y",
            "1-2 Y",
            "10-11 Y",
            "11-12 Y",
            "12-13 Y",
            "13-14 Y",
            "40",
            "41",
            "3-6 M",
            "0-3 M",
            "39",
            "6-12 M",
            "14-15 Y",
            "15-16 Y",
            "XXS"
        ],
        "dynamic_numeric_range": false
    },
    "rtsSize_uFilter": {
        "filter_name": "RTS Size",
        "facet_name": "rtsSize_uFilter",
        "values": [
            "FREE SIZE",
            "M",
            "L",
            "S",
            "XL",
            "XS",
            "XXL",
            "3XL",
            "4XL",
            "5XL",
            "5-6 Y",
            "3-4 Y",
            "4-5 Y",
            "7-8 Y",
            "6-7 Y",
            "6XL",
            "2-3 Y",
            "9-10 Y",
            "1-2 Y",
            "8-9 Y",
            "11-12 Y",
            "10-11 Y",
            "12-13 Y",
            "13-14 Y",
            "6-12 M",
            "40",
            "41",
            "3-6 M",
            "14-15 Y",
            "0-3 M",
            "15-16 Y",
            "2.6"
        ],
        "dynamic_numeric_range": false
    },
    "rtsSizeRow_uFilter": {
        "filter_name": "RTS Size ROW",
        "facet_name": "rtsSizeRow_uFilter",
        "values": [
            "FREE SIZE",
            "M",
            "L",
            "S",
            "XL",
            "XS",
            "XXL",
            "3XL",
            "4XL",
            "5XL",
            "5-6 Y",
            "3-4 Y",
            "4-5 Y",
            "7-8 Y",
            "6-7 Y",
            "6XL",
            "2-3 Y",
            "9-10 Y",
            "1-2 Y",
            "8-9 Y",
            "11-12 Y",
            "10-11 Y",
            "12-13 Y",
            "13-14 Y",
            "6-12 M",
            "40",
            "41",
            "3-6 M",
            "14-15 Y",
            "0-3 M",
            "15-16 Y",
            "2.6"
        ],
        "dynamic_numeric_range": false
    },
    "rtsSizeUsa_uFilter": {
        "filter_name": "RTS Size USA",
        "facet_name": "rtsSizeUsa_uFilter",
        "values": [
            "FREE SIZE",
            "M",
            "L",
            "S",
            "XL",
            "XS",
            "XXL",
            "3XL",
            "4XL",
            "5XL",
            "5-6 Y",
            "3-4 Y",
            "4-5 Y",
            "7-8 Y",
            "6-7 Y",
            "6XL",
            "2-3 Y",
            "9-10 Y",
            "1-2 Y",
            "8-9 Y",
            "11-12 Y",
            "10-11 Y",
            "12-13 Y",
            "13-14 Y",
            "6-12 M",
            "40",
            "41",
            "3-6 M",
            "14-15 Y",
            "0-3 M"
        ],
        "dynamic_numeric_range": false
    },
    "warehouseSizeUsa_uFilter": {
        "filter_name": "USA Warehouse Size",
        "facet_name": "warehouseSizeUsa_uFilter",
        "values": [
            "M",
            "S",
            "L",
            "XL",
            "XS",
            "XXL",
            "3XL",
            "4XL",
            "6XL",
            "FREE SIZE",
            "5XL",
            "39",
            "1-2 Y",
            "11-12 Y",
            "37",
            "38",
            "8-9 Y",
            "XXS",
            "10-11 Y",
            "40"
        ],
        "dynamic_numeric_range": false
    },
    "discountSize_uFilter": {
        "filter_name": "Discount Size",
        "facet_name": "discountSize_uFilter",
        "values": [
            "M",
            "L",
            "S",
            "XL",
            "XXL",
            "XS",
            "3XL",
            "FREE SIZE",
            "4XL",
            "5XL",
            "6XL",
            "6-7 Y",
            "5-6 Y",
            "7-8 Y",
            "3-4 Y",
            "4-5 Y",
            "9-10 Y",
            "8-9 Y",
            "2-3 Y",
            "1-2 Y",
            "10-11 Y",
            "11-12 Y",
            "12-13 Y",
            "13-14 Y",
            "6-12 M",
            "3-6 M",
            "0-3 M",
            "14-15 Y",
            "40",
            "39"
        ],
        "dynamic_numeric_range": false
    },
    "discountSizeUsa_uFilter": {
        "filter_name": "Discount Size USA",
        "facet_name": "discountSizeUsa_uFilter",
        "values": [
            "M",
            "L",
            "S",
            "XL",
            "XXL",
            "XS",
            "3XL",
            "4XL",
            "FREE SIZE",
            "5XL",
            "6XL",
            "6-7 Y",
            "5-6 Y",
            "7-8 Y",
            "3-4 Y",
            "4-5 Y",
            "9-10 Y",
            "8-9 Y",
            "2-3 Y",
            "1-2 Y",
            "10-11 Y",
            "11-12 Y",
            "12-13 Y",
            "13-14 Y",
            "6-12 M",
            "3-6 M",
            "0-3 M",
            "14-15 Y",
            "40",
            "39"
        ],
        "dynamic_numeric_range": false
    },
    "discountSizeRow_uFilter": {
        "filter_name": "Discount Size ROW",
        "facet_name": "discountSizeRow_uFilter",
        "values": [
            "M",
            "L",
            "S",
            "XL",
            "XXL",
            "XS",
            "3XL",
            "4XL",
            "FREE SIZE",
            "5XL",
            "6XL",
            "6-7 Y",
            "5-6 Y",
            "7-8 Y",
            "3-4 Y",
            "4-5 Y",
            "9-10 Y",
            "8-9 Y",
            "2-3 Y",
            "1-2 Y",
            "10-11 Y",
            "11-12 Y",
            "12-13 Y",
            "13-14 Y",
            "6-12 M",
            "3-6 M",
            "0-3 M",
            "14-15 Y",
            "40",
            "39"
        ],
        "dynamic_numeric_range": false
    },
    "baseColor_uFilter": {
        "filter_name": "Color",
        "facet_name": "baseColor_uFilter",
        "values": [
            "Gold",
            "Green",
            "Black",
            "Pink",
            "Blue",
            "Yellow",
            "White",
            "Beige",
            "Off White",
            "Cream",
            "Multicolor",
            "Red",
            "Sky Blue",
            "Silver",
            "Purple",
            "Brown",
            "Peach",
            "Ivory",
            "Magenta",
            "Wine",
            "Orange",
            "Grey",
            "Maroon",
            "Fuchsia",
            "Coral",
            "Olive",
            "Teal",
            "Mint",
            "Lavender",
            "Mustard",
            "Tan"
        ],
        "dynamic_numeric_range": false
    },
    "estimatedDeliveryWeek_uFilter": {
        "filter_name": "Shipping Time",
        "facet_name": "estimatedDeliveryWeek_uFilter",
        "values": [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5"
        ],
        "dynamic_numeric_range": false
    },
    "shopByOccassion_uFilter": {
        "filter_name": "Occasion",
        "facet_name": "shopByOccassion_uFilter",
        "values": [
            "Festive",
            "Party",
            "Wedding",
            "Brunch",
            "Cocktail",
            "Sangeet",
            "Reception",
            "Engagement Party",
            "Mehendi",
            "Resort",
            "Haldi",
            "Puja",
            "Destination Wedding",
            "Festive & Wedding",
            "Bride",
            "Work",
            "Groom",
            "Loungewear",
            "Bridesmaid",
            "After Party",
            "Engagement",
            "Athleisure",
            "Mehendi & Haldi",
            "Groomsmen",
            "Cocktail & Reception",
            "Sleepwear",
            "Evening"
        ],
        "dynamic_numeric_range": false
    },
    "classificationTag_uFilter": {
        "filter_name": "Styles",
        "facet_name": "classificationTag_uFilter",
        "values": [
            "Indian",
            "Western",
            "Fusion",
            "Contemporary"
        ],
        "dynamic_numeric_range": false
    },
    "baseFabricMaterial_uFilter": {
        "filter_name": "Fabric/Material",
        "facet_name": "baseFabricMaterial_uFilter",
        "values": [
            "Cotton",
            "Chanderi",
            "Organza",
            "Silk",
            "Georgette",
            "Crepe",
            "Linen",
            "Net",
            "Chiffon",
            "Satin",
            "Stone",
            "Gold",
            "Velvet",
            "Crystal",
            "Brass",
            "Silver",
            "Leather",
            "Brocade",
            "Zari",
            "Handloom Cotton",
            "Denim",
            "Modal",
            "Lace",
            "Jacquard",
            "Cotton Silk",
            "Wool",
            "Muslin",
            "Metal",
            "Banarasi",
            "Raw Silk",
            "Tissue",
            "Lycra",
            "Dupion",
            "Bamboo",
            "Gold Plated",
            "Kota Doria",
            "Chinon",
            "Alloy",
            "Jersey",
            "Suede",
            "Bemberg",
            "Mesh",
            "Tulle",
            "Neoprene",
            "Polyester",
            "Cotton Linen",
            "Viscose",
            "Silk Tissue",
            "Silk Linen",
            "Faux Leather",
            "Hemp",
            "Lurex",
            "Nylon",
            "Pashmina",
            "Glass",
            "Knit",
            "Mukaish",
            "Cashmere",
            "Silk Velvet",
            "Maheshwari",
            "Microfiber",
            "Poplin",
            "Gingham",
            "Copper",
            "Patola",
            "Corduroy",
            "Jamdani",
            "Tussar Silk",
            "Oxford",
            "Gabardine",
            "Gemstone",
            "Matka Silk",
            "Bronze",
            "Tweed",
            "Vegan Leather",
            "Canvas",
            "Rayon",
            "Art Silk",
            "Cambric",
            "Mohair",
            "Acrylic",
            "Crinkle",
            "Jute",
            "Faux Fur",
            "Kanjeevaram Silk",
            "Cotton Satin",
            "Fur",
            "Lampi",
            "Silk Chanderi",
            "Fleece",
            "Flannel",
            "Doriya",
            "cotton",
            "Mulmul",
            "Taffeta",
            "Habutai Silk",
            "Chanderi Silk",
            "Organza Tissue",
            "Cotton Jacquard",
            "Silk Wool",
            "Silk Organza",
            "Cotton Chanderi",
            "Chanderi Organza",
            "Cotton Cambric",
            "Crepe Chinon",
            "Cotton Net",
            "Georgette Net",
            "Fabric",
            "Chiffon Crepe",
            "Cotton Muslin",
            "Cotton Organza",
            "linen",
            "Crepe Net",
            "Organza Crepe",
            "Organza Georgette",
            "Organza Brocade",
            "Organza Net",
            "Georgette Crepe",
            "Chanderi Net",
            "Cotton Georgette",
            "Crepe Wool",
            "Organza Linen",
            "Satin Net",
            "Chanderi Wool",
            "Chanderi Linen",
            "Satin Linen",
            "Silk Crepe",
            "Cotton Crepe",
            "Organza Chiffon",
            "organza",
            "Chanderi Brocade",
            "Chanderi Crepe",
            "Cotton Bamboo",
            "Cotton Denim",
            "Organza Satin",
            "Silk Chiffon",
            "Silk Satin",
            "Silver Copper",
            "Blend Fabrics",
            "Chiffon Jersey",
            "Chiffon Net",
            "Chiffon Satin",
            "Cotton Chanderi Silk",
            "Cotton Lycra",
            "Crepe Velvet",
            "Georgette Chiffon",
            "Georgette Jacquard",
            "Metal Alloy",
            "Organza Lycra",
            "Organza Velvet"
        ],
        "dynamic_numeric_range": false
    },
    "celebrity_uFilter": {
        "filter_name": "Celebrity",
        "facet_name": "celebrity_uFilter",
        "values": [
            "Shilpa Shetty",
            "Rakul Preet Singh",
            "Sonakshi Sinha",
            "Aditi Rao Hydari",
            "Bhumi Pednekar",
            "Diana Penty",
            "Madhuri Dixit",
            "Karishma Tanna",
            "Mrunal Thakur",
            "Kajol",
            "Mouni Roy",
            "Huma Qureshi",
            "Malaika Arora",
            "Aamna Sharif",
            "Dia Mirza",
            "Kriti Sanon",
            "Manushi Chhillar",
            "Sanya Malhotra",
            "Alia Bhatt",
            "Chitrangada Singh",
            "Shalini Passi",
            "Arushi Mehra",
            "Khushi Kapoor",
            "Kusha Kapila",
            "Sakshi Sindhwani",
            "Janhvi Kapoor",
            "Medha Shankr",
            "Sara Ali Khan",
            "Vishal Jethwa",
            "Ahsaas Channa",
            "Alaviaa Jaffrey",
            "Anjali Sivaraman",
            "Ayesha Amin Nigam",
            "Ayesha Kanga",
            "Hania Aamir"
        ],
        "dynamic_numeric_range": false
    },
    "price": {
        "filter_name": "Price",
        "facet_name": "price",
        "values": [],
        "dynamic_numeric_range": true
    },
    "attrLengthSleeve_uFilter": {
        "filter_name": "Sleeve Length",
        "facet_name": "attrLengthSleeve_uFilter",
        "values": [
            "Full Sleeves",
            "Sleeveless",
            "Three-Quarter Sleeves",
            "Half Sleeves",
            "Cap Sleeves",
            "Cape Sleeve"
        ],
        "dynamic_numeric_range": false
    },
    "attrNeckline_uFilter": {
        "filter_name": "Neckline Style",
        "facet_name": "attrNeckline_uFilter",
        "values": [
            "Round Neck",
            "V-Neck",
            "Mandarin Collar",
            "Collared",
            "Sweetheart Neck",
            "Square Neck",
            "Bandeau Neck",
            "Split V-Neck",
            "Open Neck",
            "Scoop Neck",
            "Halter Neck",
            "High Neck",
            "Round",
            "Yes",
            "Asymmetric",
            "V Neck",
            "One Shoulder",
            "Plunge Neck",
            "Collared Neck",
            "Shawl Neck",
            "Keyhole Neck",
            "Boat Neck",
            "Off-Shoulder",
            "Mandarin",
            "Band",
            "Cowl Neck",
            "Button-Down Neck",
            "Band Collar",
            "Crew Neck",
            "Notched",
            "Leaf Neck",
            "Notched Neck",
            "Shirt Collar",
            "Polo Collar",
            "Collar",
            "Open",
            "Plunge V Neck",
            "U Neck",
            "Turtle Neck",
            "Boat",
            "Spread Collar",
            "Choker Neck",
            "Lapel Collar",
            "Halter",
            "Jacket: Open",
            "Cape: open",
            "Notched Lapel",
            "Asymmetric Neck",
            "Notched Collar",
            "Stand Collar",
            "Point Collar",
            "No",
            "Peter Pan Collar",
            "Collarless",
            "Deep Neck",
            "Turn-Down Collar",
            "Wing Collar",
            "Club Collar",
            "Standard Collar"
        ],
        "dynamic_numeric_range": false
    },
    "quickFilters_uFilter": {
        "filter_name": "Quick Filters",
        "facet_name": "quickFilters_uFilter",
        "values": [
            "customizable",
            "discountedProduct",
            "discountedProductRow",
            "discountedProductUsa",
            "productActivatedInLast60Days",
            "rts",
            "rtsRow",
            "rtsUsa",
            "virtualTryonAvailable"
        ],
        "dynamic_numeric_range": false
    },
    "waistRise_uFilter": {
        "filter_name": "Waist/Rise",
        "facet_name": "waistRise_uFilter",
        "values": [
            "Regular Waist",
            "High Waist",
            "Elasticated Waist",
            "Drawstring Waist",
            "0",
            "Low Waist",
            "regular_waist"
        ],
        "dynamic_numeric_range": false
    },
    "fit_uFilter": {
        "filter_name": "Fit",
        "facet_name": "fit_uFilter",
        "values": [
            "Regular Fit",
            "Flared",
            "Relaxed Fit",
            "A-Line",
            "Tailored Fit",
            "Straight Cut",
            "Oversized",
            "Draped Fit",
            "Slim Fit",
            "Boxy Fit",
            "Bodycon",
            "0",
            "draped_fit",
            "straight_cut"
        ],
        "dynamic_numeric_range": false
    }
});
