// Generated from the original sales prompt filter master.
// Keep catalog values exact; update this registry when Solr facets change.
'use strict';

module.exports = Object.freeze({
    "audience_uFilter": {
        "filter_name": "Gender",
        "facet_name": "audience_uFilter",
        "values": [
            "Women",
            "Men",
            "Girls",
            "Boys"
        ],
        "dynamic_numeric_range": false
    },
    "level2CategoryName_uFilter": {
        "filter_name": "Category",
        "facet_name": "level2CategoryName_uFilter",
        "values": [
            "Kurta Sets",
            "Dresses",
            "Topwear",
            "Lehengas",
            "Sarees",
            "Pant Sets",
            "Earrings",
            "Bottomwear",
            "Jackets And Sets",
            "Kurtas",
            "Sherwanis",
            "Bags",
            "Co-Ord Sets",
            "Necklaces",
            "Ethnic Co-Ord Sets",
            "Jewellery Sets",
            "Ethnic Dresses",
            "Bandhgalas",
            "Rings",
            "Footwear",
            "Gowns",
            "Blazers & Sets",
            "Suits And Tuxedos",
            "Ethnic Jackets",
            "Brooches And Pins",
            "Scarves & Stoles",
            "Jumpsuits",
            "Bangles",
            "Dupattas",
            "Maang Tikkas",
            "Bracelets",
            "Coats And Waistcoats",
            "Co-ord Sets",
            "Ethnic Co-ord Sets",
            "Kalangis",
            "Hathphools",
            "Shawls",
            "Vests",
            "Belts",
            "Matha Pattis",
            "Bow Ties And Pocket Square Sets",
            "Nose Rings",
            "Swimwear"
        ],
        "dynamic_numeric_range": false
    },
    "level3CategoryNames_uFilter": {
        "filter_name": "Sub Category",
        "facet_name": "level3CategoryNames_uFilter",
        "values": [
            "Straight Kurta Sets",
            "Lehenga Cholis",
            "Casual Shirts",
            "Midi Dress",
            "Maxi Dress",
            "Pre-Draped Sarees",
            "Sharara Sets",
            "Classic Kurta Sets",
            "Nehru Jacket Sets",
            "Palazzo Sets",
            "Blouses",
            "Anarkali Sets",
            "Jackets",
            "Mini Dress",
            "Dangler Earrings",
            "Kaftan Dresses",
            "Tops & Tunics",
            "Trousers",
            "Kurtas",
            "Handloom Sarees",
            "Clutches",
            "Kaftan Sets",
            "Statement Rings",
            "Tunics & Kurtis",
            "Jacket & Cape Lehengas",
            "Jacket Sets",
            "Skirts",
            "Jacket & Angarkha Kurta Sets",
            "Stud Earrings",
            "Dhoti Sets",
            "Chokers",
            "Chandbali Earrings",
            "Churidar Sets",
            "Formal Shirts",
            "Gharara Sets",
            "Blazers",
            "Salwar Sets",
            "Potlis/Batwas",
            "Palazzos",
            "Pendant Necklaces",
            "Party Gowns",
            "Half & Half Sarees",
            "Handbags",
            "Stoles",
            "Flats",
            "Bangle Sets",
            "Chandelier Earrings",
            "Blazer Sets",
            "Heels",
            "Layered Necklaces"
        ],
        "dynamic_numeric_range": false
    },
    "designerName_uFilter": {
        "filter_name": "Designers",
        "facet_name": "designerName_uFilter",
        "values": [
            "Jhambthreads",
            "Cord",
            "Three",
            "Itrh",
            "Kaveri",
            "SHAZA",
            "MATI",
            "Ilk",
            "APT FOREVER",
            "Aseem Kapoor",
            "Bauble Bazaar",
            "Riana Jewellery",
            "Saaksha & Kinni",
            "Surily G",
            "Twenty Nine",
            "Zevar By Geeta",
            "Label Niti Bothra",
            "MRJEWELS",
            "Geroo Jaipur",
            "Philocaly",
            "Sarab Khanijou",
            "Bunka",
            "Upavita",
            "Koai",
            "Line Out Line",
            "Samant Chauhan",
            "Aisha Rao",
            "Bhanuni By Jyoti",
            "Asuka",
            "Samyukta Singhania",
            "Satya Paul",
            "Amreli Jaipur",
            "Kora",
            "Karaj Jaipur",
            "NOIB",
            "Pants And Pajamas",
            "Alam By Tulsi Patel",
            "Leh Studios",
            "Seema Gujral",
            "Raghavendra Rathore Jodhpur",
            "Chandrima",
            "Punit Arora",
            "Siddartha Tytler",
            "Baise Gaba",
            "JAYANTI REDDY",
            "Roqa",
            "Shyam Narayan Prasad",
            "Perona",
            "Ridhi Mehra",
            "Dhaari",
            "Sven Suits",
            "Heartistry by Anky",
            "Moh-Maya By Disha Khatri",
            "Outhouse",
            "SALIL BHATIA",
            "Sahil Kochhar",
            "Sangeeta Boochra",
            "Basanti Kapde aur Koffee",
            "Kasbah",
            "Linen Bloom",
            "Paulmi And Harsh",
            "The Summer House",
            "House Of Kosha",
            "Khat",
            "ABRAHAM AND THAKORE",
            "Manner",
            "Rohit Doshi",
            "love",
            "Kiki",
            "Prestones",
            "ZOOP MEN",
            "Kalista",
            "Prisho",
            "Studio Rigu",
            "Neetiandmudita",
            "Raasa",
            "Cosa Nostraa",
            "Pankaj & Nidhi",
            "Kokommo",
            "Namrata Joshipura",
            "Ritu Kumar",
            "Taika By Poonam Bhagat",
            "Aneesh Agarwaal",
            "17:17 By Simmi Saboo",
            "Jodi",
            "KIHOY",
            "Madhav Agasti",
            "Stoique",
            "Mac Duggal",
            "Rajesh Pratap Singh",
            "Countrymade",
            "Doux Amour",
            "Eeda",
            "Gulabo Jaipur",
            "MR. Ajay Kumar",
            "ZiP by Payal & Zinal",
            "Amaare",
            "Chamee & Palak",
            "Anamika Khanna",
            "Do Taara",
            "Gaurav katta",
            "Payal Pratap",
            "Runit Gupta",
            "Bannhi By Priyanka Rathore",
            "Dolly J",
            "Aakaar",
            "JAYATI GOENKA",
            "Karisa Designs",
            "Meenagurnam",
            "Nikasha",
            "Vaayu",
            "Zazu",
            "ASRUMO",
            "House Of Three",
            "Khwaab By Sanjana Lakhani",
            "Pooja Rajgarhia Gupta",
            "Arihant Rai Sinha",
            "FAYON KIDS",
            "Shruti Sancheti",
            "Advait",
            "Anaash",
            "Begum",
            "ESME",
            "Pouli Pret",
            "Tiesta",
            "Brahmand By Vertika Kalra",
            "Evra By Nikita",
            "Hirika & Dhruti",
            "Masaba",
            "Shwetanga",
            "Nikita Mhaisalkar",
            "Priyaa",
            "Ampm",
            "EASE",
            "Himani Punatar",
            "Kaaj Button",
            "Millionaire",
            "Payal and Rishab",
            "Wabi Sabi By Anshum-Ritesh",
            "ANGAD SINGH",
            "Amaara Jewels",
            "Libas Cafe by Nidhi & Ashish",
            "Vedangi Agarwal",
            "Almaari By Pooja Patel",
            "Charu Makkar",
            "Kritika Dawar",
            "Mnsh",
            "Pleats By Aruni",
            "Roza",
            "Ajiesh Oberoi",
            "Ewoke",
            "Istya",
            "Jatin Malik",
            "Label Astha Chhabra",
            "Lil Drama",
            "Mahima Mahajan",
            "Mani Bhatia",
            "Moh India",
            "Seema Thukral",
            "Shruti S",
            "Aariyana Couture",
            "Aroka",
            "Kahani Lush",
            "Tamanna Punjabi Kapoor",
            "Triune",
            "Vishwa By Pinki Sinha",
            "Amit Aggarwal",
            "Qbik",
            "Charu And Vasundhara",
            "House Of Varada",
            "Swabhimann",
            "Arcvsh By Pallavi Singh",
            "Gauri & Nainika",
            "Mukti And Kavith Casa",
            "OMI",
            "PRERTO",
            "Richa Khemka",
            "Ritika Mirchandani",
            "Taisha",
            "Trendy Tokari",
            "Xago",
            "Aditi Gupta",
            "Ahi Clothing",
            "Madder Much",
            "Manish Nagdeo",
            "Myoho",
            "Shivani Awasty",
            "Mamma Plz",
            "Mishru",
            "Monika Mathuria Datta",
            "Petite Pomme",
            "Anmol Kakad",
            "Honey&Me",
            "MINIME ORGANICS",
            "Poochkie",
            "Bijoux By Priya Chandna",
            "Disha Muchhala",
            "Label Priyanka Kar",
            "Label Shristi Chetani",
            "Little Loom",
            "Nautanky",
            "Nero India",
            "Oja",
            "Rabani & Rakha",
            "Drishti & Zahabia",
            "Echostudio",
            "FOREVER NOOR",
            "Indigo Dreams",
            "Opus Atelier",
            "Shikha Mehta",
            "Agraj Jain",
            "Apeksha Jain Label",
            "Banana Labs",
            "Dot",
            "Isharya",
            "Jigar & Nikita",
            "Nayaab By Sonia",
            "Prata",
            "Thetaa",
            "Etasha By Asha Jain",
            "LAHARIO",
            "Nitika Gujral",
            "Pomcha Jaipur",
            "Pooja Peshoria",
            "Roohbyridhimaa",
            "Studio 113",
            "Two Sisters By Gyans",
            "Chotibuti",
            "House Of Fett",
            "Mustard Moon By Neyha And Vrinda",
            "RI.Ritu Kumar",
            "Shetab Kazmi",
            "Soleart",
            "Basil Leaf",
            "Charkhee",
            "MAISARA JEWELRY",
            "Pasha India",
            "Prahnaaya",
            "Style Junkiie",
            "Tanu Malhotra",
            "Vana Ethnics",
            "Vidhi Wadhwani",
            "Cupid Cotton",
            "KEITH GOMES",
            "Kalp",
            "Kanj By Priyanka A Sakhuja",
            "Minaki",
            "Pankhuri By Priyanka",
            "Sue Mue",
            "Daljit Sudan",
            "Mimamsaa",
            "Rohit Bal",
            "Sarang Kaur",
            "Beige",
            "Chal Jooti",
            "Design O Stitch",
            "Tiber Taber",
            "arani label",
            "Casa Ninos",
            "Jyoti Sachdev Iyer",
            "Kalakaari By Sagarika",
            "Krishna Padia",
            "Shahmeen Husain",
            "Wazir C",
            "Origani",
            "Sandalwali",
            "Spring Break",
            "Tarun Tahiliani",
            "Dilnaz",
            "Free Sparrow",
            "Orthodox",
            "Priya Chaudhary",
            "Queens Jewels",
            "Raw & Rustic By Niti Bothra",
            "Sajeda A Lehry",
            "Surkh Syahi",
            "Weaver Story",
            "Mint N Oranges",
            "Prevasu",
            "Show Shaa",
            "Tiny Colour",
            "PAARSH",
            "Sheetal Batra",
            "The Right Cut",
            "House Of Koa",
            "Punit Balana",
            "Domani",
            "Kiyohra",
            "Lacquer Embassy",
            "Sonali Methi",
            "COUTURE BY NIHARIKA",
            "Nafs",
            "Chaashni By Maansi And Ketan",
            "Kharakapas",
            "SG Collection By Sonia Gulrajani",
            "Sole Mates by Palak",
            "Tan & Loom",
            "Toplove",
            "Archana Kochhar",
            "Son Of A Noble Snob",
            "Fairies Forever",
            "OFRIDA",
            "Amrit Dawani",
            "Anita Dongre",
            "Anshika Tak Label",
            "Dash And Dot",
            "Geisha Designs",
            "JILMIL DREAMWEAR",
            "Krishna Mehta",
            "Neha Khullar",
            "Nikunj By NIIDHI BAJAJ",
            "Osaa By Adarsh"
        ],
        "dynamic_numeric_range": false
    },
    "attrPattern_uFilter": {
        "filter_name": "Pattern",
        "facet_name": "attrPattern_uFilter",
        "values": [
            "Floral",
            "Solid",
            "Ornamental",
            "Symmetrical",
            "Embroidered"
        ],
        "dynamic_numeric_range": false
    },
    "attrTypeOfWork_uFilter": {
        "filter_name": "Type of Work",
        "facet_name": "attrTypeOfWork_uFilter",
        "values": [
            "Embroidery",
            "Beads",
            "Sequins",
            "Zari",
            "Pearls",
            "Stones",
            "Tassels",
            "Mirrors",
            "Crystals",
            "Applique",
            "Lace",
            "Gota Patti",
            "Cut work",
            "Fabric Flowers",
            "Fringe",
            "Smocking",
            "Gemstones",
            "Rhinestones",
            "Ruffles",
            "Chains",
            "Metallic Thread",
            "Foil Printing",
            "Patchwork",
            "Brooches",
            "Pom-poms",
            "Zardozi",
            "Piping",
            "Studs",
            "Faux Diamonds",
            "Bows",
            "Thread Embroidery",
            "Printed",
            "Diamonds",
            "Feathers",
            "Machine Embroidery",
            "Resham Embroidery",
            "Buckles",
            "Mirror Work",
            "Digital Print",
            "Enamel",
            "Glitter",
            "Chikankari",
            "Dabka Work",
            "Embroidered",
            "Pitta Work",
            "Aari Taari",
            "Block Print",
            "Cross Stitch",
            "Dabka",
            "Hand Painted"
        ],
        "dynamic_numeric_range": false
    },
    "size_uFilter": {
        "filter_name": "Size",
        "facet_name": "size_uFilter",
        "values": [
            "L",
            "M",
            "XL",
            "S",
            "XS",
            "XXL",
            "3XL",
            "4XL",
            "5XL",
            "6XL",
            "FREE SIZE",
            "4-5 Y",
            "2-3 Y",
            "6-7 Y",
            "5-6 Y",
            "7-8 Y",
            "3-4 Y",
            "8-9 Y",
            "9-10 Y",
            "10-11 Y",
            "1-2 Y",
            "11-12 Y",
            "12-13 Y",
            "13-14 Y",
            "14-15 Y",
            "15-16 Y",
            "XXS",
            "0-3 M",
            "3-6 M",
            "6-12 M"
        ],
        "dynamic_numeric_range": false
    },
    "rtsSize_uFilter": {
        "filter_name": "RTS Size",
        "facet_name": "rtsSize_uFilter",
        "values": [
            "FREE SIZE",
            "L",
            "M",
            "XL",
            "S",
            "XXL",
            "XS",
            "3XL",
            "7-8 Y",
            "5-6 Y",
            "6-7 Y",
            "2-3 Y",
            "3-4 Y",
            "4-5 Y",
            "9-10 Y",
            "1-2 Y",
            "4XL",
            "5XL",
            "6XL",
            "8-9 Y",
            "11-12 Y",
            "13-14 Y",
            "10-11 Y",
            "12-13 Y",
            "14-15 Y",
            "6-12 M",
            "0-3 M",
            "3-6 M",
            "15-16 Y",
            "2.6"
        ],
        "dynamic_numeric_range": false
    },
    "rtsSizeRow_uFilter": {
        "filter_name": "RTS Size ROW",
        "facet_name": "rtsSizeRow_uFilter",
        "values": [
            "FREE SIZE",
            "L",
            "M",
            "XL",
            "S",
            "XXL",
            "XS",
            "3XL",
            "7-8 Y",
            "5-6 Y",
            "6-7 Y",
            "2-3 Y",
            "3-4 Y",
            "4-5 Y",
            "9-10 Y",
            "1-2 Y",
            "4XL",
            "5XL",
            "6XL",
            "8-9 Y",
            "11-12 Y",
            "13-14 Y",
            "10-11 Y",
            "12-13 Y",
            "14-15 Y",
            "6-12 M",
            "0-3 M",
            "3-6 M",
            "15-16 Y",
            "2.6"
        ],
        "dynamic_numeric_range": false
    },
    "rtsSizeUsa_uFilter": {
        "filter_name": "RTS Size USA",
        "facet_name": "rtsSizeUsa_uFilter",
        "values": [
            "FREE SIZE",
            "L",
            "M",
            "XL",
            "S",
            "XXL",
            "XS",
            "3XL",
            "7-8 Y",
            "5-6 Y",
            "6-7 Y",
            "2-3 Y",
            "3-4 Y",
            "4-5 Y",
            "9-10 Y",
            "1-2 Y",
            "4XL",
            "5XL",
            "6XL",
            "8-9 Y"
        ],
        "dynamic_numeric_range": false
    },
    "discountSize_uFilter": {
        "filter_name": "Discount Size",
        "facet_name": "discountSize_uFilter",
        "values": [
            "L",
            "XL",
            "M",
            "S",
            "XXL",
            "XS",
            "3XL",
            "FREE SIZE",
            "4XL",
            "5XL",
            "6XL",
            "3-4 Y",
            "4-5 Y",
            "5-6 Y",
            "6-7 Y",
            "7-8 Y",
            "2-3 Y",
            "9-10 Y",
            "11-12 Y",
            "10-11 Y"
        ],
        "dynamic_numeric_range": false
    },
    "discountSizeUsa_uFilter": {
        "filter_name": "Discount Size USA",
        "facet_name": "discountSizeUsa_uFilter",
        "values": [
            "L",
            "XL",
            "M",
            "S",
            "XXL",
            "XS",
            "3XL",
            "FREE SIZE",
            "1-2 Y",
            "10-11 Y",
            "11-12 Y",
            "2-3 Y",
            "3-4 Y",
            "4-5 Y",
            "5-6 Y",
            "6-7 Y",
            "7-8 Y",
            "8-9 Y",
            "9-10 Y",
            "4XL"
        ],
        "dynamic_numeric_range": false
    },
    "discountSizeRow_uFilter": {
        "filter_name": "Discount Size ROW",
        "facet_name": "discountSizeRow_uFilter",
        "values": [
            "L",
            "XL",
            "M",
            "S",
            "XXL",
            "XS",
            "3XL",
            "FREE SIZE",
            "1-2 Y",
            "10-11 Y",
            "11-12 Y",
            "2-3 Y",
            "3-4 Y",
            "4-5 Y",
            "5-6 Y",
            "6-7 Y",
            "7-8 Y",
            "8-9 Y",
            "9-10 Y",
            "4XL"
        ],
        "dynamic_numeric_range": false
    },
    "baseColor_uFilter": {
        "filter_name": "Color",
        "facet_name": "baseColor_uFilter",
        "values": [
            "Gold",
            "Green",
            "Black",
            "Blue",
            "Pink",
            "Beige",
            "Multicolor",
            "Off White",
            "Cream",
            "White",
            "Yellow",
            "Brown",
            "Red",
            "Sky Blue",
            "Purple",
            "Silver",
            "Ivory",
            "Peach",
            "Wine",
            "Magenta",
            "Grey",
            "Orange",
            "Maroon",
            "Coral",
            "Fuchsia",
            "Olive",
            "Teal"
        ],
        "dynamic_numeric_range": false
    },
    "estimatedDeliveryWeek_uFilter": {
        "filter_name": "Shipping Time",
        "facet_name": "estimatedDeliveryWeek_uFilter",
        "values": [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5"
        ],
        "dynamic_numeric_range": false
    },
    "shopByOccassion_uFilter": {
        "filter_name": "Occasion",
        "facet_name": "shopByOccassion_uFilter",
        "values": [
            "Festive",
            "Party",
            "Cocktail",
            "Brunch",
            "Wedding",
            "Work",
            "Reception",
            "Festive & Wedding",
            "Resort",
            "Sangeet",
            "Loungewear",
            "Groom",
            "Bride",
            "Haldi",
            "Puja",
            "Cocktail & Reception",
            "Mehendi",
            "Mehendi & Haldi",
            "Engagement",
            "Destination Wedding",
            "Athleisure",
            "Bridesmaid",
            "Sleepwear"
        ],
        "dynamic_numeric_range": false
    },
    "classificationTag_uFilter": {
        "filter_name": "Styles",
        "facet_name": "classificationTag_uFilter",
        "values": [
            "Indian",
            "Western",
            "Fusion",
            "Contemporary"
        ],
        "dynamic_numeric_range": false
    },
    "baseFabricMaterial_uFilter": {
        "filter_name": "Fabric/Material",
        "facet_name": "baseFabricMaterial_uFilter",
        "values": [
            "Cotton",
            "Linen",
            "Chanderi",
            "Organza",
            "Net",
            "Silk",
            "Crepe",
            "Georgette",
            "Chiffon",
            "Satin",
            "Silk Chanderi",
            "Denim",
            "Handloom Cotton",
            "Chanderi Silk",
            "Cotton Silk",
            "Brass",
            "Velvet",
            "Cotton Satin",
            "Wool",
            "Brocade",
            "Jacquard",
            "Chinon",
            "Silk Organza",
            "Cotton Chanderi",
            "Cotton Linen",
            "Muslin",
            "Modal",
            "Dupion",
            "Chanderi Organza",
            "Cotton Cambric",
            "Cambric",
            "Crepe Chinon",
            "Lycra",
            "Silver",
            "Cotton Net",
            "Gold",
            "Georgette Net",
            "Fabric",
            "Chiffon Crepe",
            "Cotton Muslin",
            "Cotton Organza",
            "Jersey",
            "Corduroy",
            "Leather",
            "linen",
            "Alloy",
            "Crepe Net",
            "Knit",
            "Organza Crepe",
            "Organza Georgette",
            "Cashmere",
            "Hemp",
            "Organza Brocade",
            "Organza Net",
            "cotton",
            "Georgette Crepe",
            "Kota Doria",
            "Metal",
            "Bemberg",
            "Chanderi Net",
            "Cotton Georgette",
            "Crepe Wool",
            "Lurex",
            "Microfiber",
            "Organza Linen",
            "Satin Net",
            "Chanderi Wool",
            "Silk Linen",
            "Chanderi Linen",
            "Satin Linen",
            "Silk Crepe",
            "Cotton Crepe",
            "Neoprene",
            "Organza Chiffon",
            "organza",
            "Chanderi Brocade",
            "Chanderi Crepe",
            "Cotton Bamboo",
            "Cotton Denim",
            "Lace",
            "Organza Satin",
            "Silk Chiffon",
            "Silk Satin",
            "Silk Wool",
            "Silver Copper",
            "Bamboo",
            "Blend Fabrics",
            "Chiffon Jersey",
            "Chiffon Net",
            "Chiffon Satin",
            "Cotton Chanderi Silk",
            "Cotton Lycra",
            "Crepe Velvet",
            "Gabardine",
            "Georgette Chiffon",
            "Georgette Jacquard",
            "Gold Plated",
            "Metal Alloy",
            "Organza Lycra",
            "Organza Velvet"
        ],
        "dynamic_numeric_range": false
    },
    "celebrity_uFilter": {
        "filter_name": "Celebrity",
        "facet_name": "celebrity_uFilter",
        "values": [
            "Bhumi Pednekar",
            "Shalini Passi",
            "Arushi Mehra",
            "Khushi Kapoor",
            "Kusha Kapila",
            "Sakshi Sindhwani",
            "Janhvi Kapoor",
            "Medha Shankr",
            "Sanya Malhotra",
            "Sara Ali Khan",
            "Shilpa Shetty",
            "Sonakshi Sinha",
            "Vishal Jethwa",
            "Ahsaas Channa",
            "Alaviaa Jaffrey",
            "Anjali Sivaraman",
            "Ayesha Amin Nigam",
            "Ayesha Kanga",
            "Diana Penty",
            "Hania Aamir"
        ],
        "dynamic_numeric_range": false
    },
    "price": {
        "filter_name": "Price",
        "facet_name": "price",
        "values": [],
        "dynamic_numeric_range": true
    },
    "attrLengthSleeve_uFilter": {
        "filter_name": "Sleeve Length",
        "facet_name": "attrLengthSleeve_uFilter",
        "values": [
            "Full Sleeves",
            "Sleeveless",
            "Three-Quarter Sleeves",
            "Half Sleeves",
            "Cap Sleeves"
        ],
        "dynamic_numeric_range": false
    },
    "attrNeckline_uFilter": {
        "filter_name": "Neckline Style",
        "facet_name": "attrNeckline_uFilter",
        "values": [
            "Mandarin Collar",
            "V-Neck",
            "Round Neck",
            "Collared",
            "Yes",
            "Sweetheart Neck",
            "High Neck",
            "Square Neck",
            "Halter Neck",
            "Split V-Neck",
            "Scoop Neck",
            "Open Neck",
            "One Shoulder",
            "Bandeau Neck",
            "Keyhole Neck",
            "Shawl Neck",
            "Boat Neck",
            "Notched Neck",
            "Button-Down Neck",
            "Plunge Neck",
            "Cowl Neck",
            "Off-Shoulder",
            "Crew Neck",
            "Asymmetric",
            "Band Collar",
            "Choker Neck",
            "Point Collar",
            "No",
            "Polo Collar",
            "Leaf Neck",
            "Stand Collar",
            "Turtle Neck",
            "Peter Pan Collar",
            "Collarless",
            "Deep Neck",
            "Turn-Down Collar",
            "Wing Collar",
            "Club Collar",
            "Spread Collar",
            "Standard Collar"
        ],
        "dynamic_numeric_range": false
    },
    "quickFilters_uFilter": {
        "filter_name": "Quick Filters",
        "facet_name": "quickFilters_uFilter",
        "values": [
            "customizable",
            "discountedProduct",
            "discountedProductRow",
            "discountedProductUsa",
            "productActivatedInLast60Days",
            "rts",
            "rtsRow",
            "rtsUsa",
            "virtualTryonAvailable"
        ],
        "dynamic_numeric_range": false
    },
    "waistRise_uFilter": {
        "filter_name": "Waist/Rise",
        "facet_name": "waistRise_uFilter",
        "values": [
            "Regular Waist",
            "High Waist",
            "Elasticated Waist",
            "Drawstring Waist",
            "0",
            "Low Waist",
            "regular_waist"
        ],
        "dynamic_numeric_range": false
    },
    "fit_uFilter": {
        "filter_name": "Fit",
        "facet_name": "fit_uFilter",
        "values": [
            "Regular Fit",
            "Flared",
            "Relaxed Fit",
            "A-Line",
            "Tailored Fit",
            "Straight Cut",
            "Oversized",
            "Draped Fit",
            "Slim Fit",
            "Boxy Fit",
            "Bodycon",
            "0",
            "draped_fit",
            "straight_cut"
        ],
        "dynamic_numeric_range": false
    }
});
